Webserver
hivecom/pokebot pull request #33
Opened 2020-02-11 15:06 UTC by Jokler

**Summary**
This PR implements the following **features**

- [x] Webserver based on actix
- [x] Adds duration and thumbnail information to `AudioMetadata`
- [x] Demo site to show of the information available
- [x] Tmtu-mode, a simple site based on tables (without a button to leave it again) created by @fkaa 
- [x] Easily extendable with more front-ends the user can switch between
- [x] Simple API to display the available information
- [x] Replaces all Mutexes with RwLocks to allow the website to read from multiple threads at once
- [ ] Application sometimes fails to shutdown on SIGINT/SIGTERM
- [ ] more?

**Closing issues**
Resolves #8

2020-02-12 01:23 UTC, Jokler commented on src/playlist.rs
> +        res.reverse();
There is probably a better way but I can't be bothered right now.

2020-02-22 16:45 UTC, fkaa requested changes
Run cargo fmt and put web stuff in its own folder instead of the root

2020-02-22 16:45 UTC, fkaa commented on Cargo.toml
> +rand            = { version = "0.7.3", features = ["small_rng"] }
no indenting please

2020-02-22 16:45 UTC, fkaa commented on src/audio_player.rs
> +        pipeline.set_auto_flush_bus(false);
link?

2020-02-22 16:45 UTC, fkaa commented on src/web_server.rs
> +//    }
unused?

2020-02-22 17:30 UTC, Jokler commented on src/audio_player.rs
> +        pipeline.set_auto_flush_bus(false);
added

2020-02-22 22:27 UTC, merged